language: python
cache: pip

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"
install:
    - python setup.py -q install
script:
    - python setup.py check --strict --metadata
