language: python
cache: pip

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"
install:
    - pip install docutils # needed for tests
    - python setup.py -q install
script:
    - python setup.py check --restructured --strict --metadata
